--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NhanAZ/Track
build-by-default: true
branches:
- main
projects:
  Track:
    path: ""
    icon: icon.png
    lint:
      closeTag: true
      directStdout: true
      nonPsr: true
      syntaxError: false
      phpstan: true
...
