--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NhanAZ/Track
build-by-default: true
branches:
- main
projects:
  Track:
    path: ""
    icon: icon.png
    lint:
      closeTag: false
			directStdout: false
			nonPsr: false
			syntaxError: false
			phpstan: false
...
