---
name: Track
author: NhanAZ
version: 0.0.8
main: NhanAZ\Track\Main
api: 4.0.0
src-namespace-prefix: NhanAZ\Track
website: https://github.com/NhanAZ
description: Help staffs track players using commands.

permissions:
  track.tracker:
    default: op
    description: People with this permission are authorized to track player using command
...
