---
name: Track
author: NhanAZ
version: 0.0.8
api: [3.25.0]
main: NhanAZ\Track\Main
authors:
  - Nexus9265
  - Mcbeany
  - EndermanbugZJFC
website: https://github.com/NhanAZ
description: Help staffs track players using commands.

permissions:
  track:
    default: op
    children:
      track.tracker:
        description: Poeple with this permission are authorized to follow the player using the command
...
