---
name: Track
author: NhanAZ
version: 0.0.7
api: [3.25.0]
main: NhanAZ\Track\Main
authors: [Nexus9265, Mcbeany]
website: https://github.com/NhanAZ
description: Help staffs track players using commands.
...
