---
name: Track
version: 2.0.0+beta
main: NhanAZ\Track\Main
api: 4.0.0
website: https://github.com/NhanAZ
author: NhanAZ
description: Show commands used by players to staff

permissions:
  track.tracker:
    default: op
    description: Allows to see commands used by players
...
