---
name: Track
version: 1.0.0
main: NhanAZ\Track\Main
api: 4.0.0
src-namespace-prefix: NhanAZ\Track

website: https://github.com/NhanAZ
description: Allow staff to track commands used by players
author: NhanAZ
authors:
  - EndermanbugZJFC
  - Nexus9265
  - Mcbeany

softdepend:
  - InfoAPI

permissions:
  track.tracker:
    default: op
    description: Allow staff to track commands used by players
...
