---
name: Stalker
version: 2.1.1
main: NhanAZ\Stalker\Main
api: 5.0.0
website: https://github.com/NhanAZ
author: NhanAZ
description: Show commands used by players to staff

permissions:
  stalker:
    default: op
    description: Allows to see commands used by players
...
