---
# {sender} : Name of user who used command
# {command} : Command used by user
message: "<{sender}> /{command}"

# List of exception commands. (Experimental Feature)
# The commands listed below will be hidden.
# For example: /tell NhanAZ Hello World!
# will be converted to /**** ****** ***** ******
# exceptionCmds: ["register", "login", "tell"]
exceptionCmds: []
...
