---
# {sender} : Name of user who used command
# {command} : Command used by user
trackMessage: "<{sender}> /{command}"

# Clear log of commands used by players when server is started or disabled
deleteLog:
  onEnable: false
  onDisable: false

# Maximum log file size (In Megabytes)
maxSize: 16
...
